@echo off
setlocal EnableDelayedExpansion

pushd "%~dp0.."
set "PROJECT_ROOT=%CD%"
popd

if not exist "%PROJECT_ROOT%\.env" (
    echo [ERROR] No se encontro .env en: %PROJECT_ROOT%
    pause & exit /b 1
)
for /f "usebackq eol=# tokens=1,* delims==" %%A in ("%PROJECT_ROOT%\.env") do (
    if not "%%A"=="" set "%%A=%%B"
)

where gcloud >nul 2>&1
if errorlevel 1 (
    echo [ERROR] gcloud no encontrado.
    pause & exit /b 1
)

gcloud config set project %GCP_PROJECT_ID% --quiet
echo   [OK] Proyecto: %GCP_PROJECT_ID%
echo.
echo ============================================================
echo  [5/5] Deploy del Cloud Run Job
echo ============================================================
echo.
set "IMAGE_TAG=%GCP_REGION%-docker.pkg.dev/%GCP_PROJECT_ID%/%GCP_ARTIFACT_REPO%/%IMAGE_NAME%:latest"
set "SA_EMAIL=%SA_NAME%@%GCP_PROJECT_ID%.iam.gserviceaccount.com"
echo  Job   : %CLOUD_RUN_JOB_NAME%
echo  Imagen: %IMAGE_TAG%
echo  SA    : %SA_EMAIL%
echo.
gcloud run jobs describe %CLOUD_RUN_JOB_NAME% --region=%GCP_REGION% --project=%GCP_PROJECT_ID% >nul 2>&1
if errorlevel 1 ( set "JOB_CMD=create" ) else ( set "JOB_CMD=update" )
echo   Ejecutando: gcloud run jobs !JOB_CMD!...
echo.
gcloud beta run jobs !JOB_CMD! %CLOUD_RUN_JOB_NAME% --image="%IMAGE_TAG%" --region=%GCP_REGION% --project=%GCP_PROJECT_ID% --service-account=%SA_EMAIL% --gpu=1 --gpu-type=nvidia-l4 --cpu=4 --memory=16Gi --task-timeout=3600 --max-retries=1 --set-env-vars="GCP_PROJECT_ID=%GCP_PROJECT_ID%,GCS_BUCKET_INPUT=%GCS_BUCKET_INPUT%,GCS_BUCKET_OUTPUT=%GCS_BUCKET_OUTPUT%,GCS_INPUT_PREFIX=%GCS_INPUT_PREFIX%,GCS_OUTPUT_PREFIX=%GCS_OUTPUT_PREFIX%,GCS_UPLOAD_TIMEOUT_SECONDS=%GCS_UPLOAD_TIMEOUT_SECONDS%,GCS_DOWNLOAD_TIMEOUT_SECONDS=%GCS_DOWNLOAD_TIMEOUT_SECONDS%,GCS_MAX_RETRY_ATTEMPTS=%GCS_MAX_RETRY_ATTEMPTS%,APP_ENV=%APP_ENV%,LOG_LEVEL=%LOG_LEVEL%,LOG_FORMAT=%LOG_FORMAT%,VIDEO_TARGET_SCALE=%VIDEO_TARGET_SCALE%,VIDEO_OUTPUT_FPS=%VIDEO_OUTPUT_FPS%,VIDEO_OUTPUT_CRF=%VIDEO_OUTPUT_CRF%,VIDEO_OUTPUT_PRESET=%VIDEO_OUTPUT_PRESET%,VIDEO_OUTPUT_CODEC=%VIDEO_OUTPUT_CODEC%,VIDEO_OUTPUT_AUDIO_BITRATE=%VIDEO_OUTPUT_AUDIO_BITRATE%,VIDEO_OUTPUT_AUDIO_CODEC=%VIDEO_OUTPUT_AUDIO_CODEC%,ESRGAN_MODEL_NAME=%ESRGAN_MODEL_NAME%,ESRGAN_MODEL_PATH=%ESRGAN_MODEL_PATH%,ESRGAN_TILE_SIZE=%ESRGAN_TILE_SIZE%,ESRGAN_TILE_PAD=%ESRGAN_TILE_PAD%,ESRGAN_PRE_PAD=%ESRGAN_PRE_PAD%,ESRGAN_DEVICE=%ESRGAN_DEVICE%,ESRGAN_NUM_FEAT=%ESRGAN_NUM_FEAT%,ESRGAN_NUM_BLOCK=%ESRGAN_NUM_BLOCK%,ESRGAN_NUM_GROW_CH=%ESRGAN_NUM_GROW_CH%,AUDIO_ENABLE_ENHANCEMENT=%AUDIO_ENABLE_ENHANCEMENT%,AUDIO_DENOISER_STRENGTH=%AUDIO_DENOISER_STRENGTH%,AUDIO_DENOISER_PATCH_RADIUS=%AUDIO_DENOISER_PATCH_RADIUS%,AUDIO_EQ_FREQUENCY=%AUDIO_EQ_FREQUENCY%,AUDIO_EQ_GAIN_DB=%AUDIO_EQ_GAIN_DB%,AUDIO_EQ_WIDTH=%AUDIO_EQ_WIDTH%,FFMPEG_BINARY=%FFMPEG_BINARY%,FFPROBE_BINARY=%FFPROBE_BINARY%,FFMPEG_THREADS=%FFMPEG_THREADS%,FFMPEG_LOGLEVEL=%FFMPEG_LOGLEVEL%,TMP_BASE_DIR=%TMP_BASE_DIR%,FRAMES_SUBDIR=%FRAMES_SUBDIR%,FRAMES_UPSCALED_SUBDIR=%FRAMES_UPSCALED_SUBDIR%,FRAMES_FORMAT=%FRAMES_FORMAT%,AUDIO_RAW_FILENAME=%AUDIO_RAW_FILENAME%,AUDIO_CLEAN_FILENAME=%AUDIO_CLEAN_FILENAME%,INPUT_FILENAME=%INPUT_FILENAME%,STORAGE_BACKEND=%STORAGE_BACKEND%"
if errorlevel 1 ( echo. & echo   [ERROR] Deploy fallo. & pause & exit /b 1 )
echo.
echo  Job desplegado: %CLOUD_RUN_JOB_NAME%
echo  Uso diario: scripts\run.bat nombre_video.mp4
echo.
pause
